---
# tasks file for create_ovn_entities
- name: create a logical network
  os_network:
    cloud: "{{ cloud_name }}"
    state: present
    name: "{{ item.network }}"
  with_items:
    - "{{ network_points }}"
  register: created_networks

- name: attach a subnet to the logical network
  os_subnet:
    cloud: "{{ cloud_name }}"
    state: present
    network_name: "{{ item.1.network.id }}"
    name: "{{ item.0.subnet_name }}"
    ip_version: 4
    cidr: "{{ item.0.cidr }}"
    gateway_ip: "{{ item.0.gateway_ip }}"
    enable_dhcp: yes
  when:
    - item.0.subnet_name is defined
    - item.0.cidr is defined or item.0.use_default_subnetpool
  with_together:
    - "{{ network_points }}"
    - "{{ created_networks.results }}"
  register: created_subnets

- name: create ports in the logical network
  os_port:
    cloud: "{{ cloud_name }}"
    name: "{{ item.0.name }}"
    state: present
    network: "{{ item.1.network.id }}"
    fixed_ips:
      - ip_address: "{{ item.0.ip }}"
    mac_address: "{{ item.0.mac }}"
  with_together:
    - "{{ network_points }}"
    - "{{ created_networks.results }}"
